# ~/.config/starship.toml

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$nodejs\
$python\
$docker_context\
"""

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#FF79C6"
format = '[$user ]($style)📂 '
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
symbols.Debian = '  '
disabled = false

[directory]
truncation_length = 0
truncation_symbol = '~/'

[c]
symbol = " "
format = 'via [ $symbol ($version) ]($style)'

[docker_context]
symbol = "🐳 "
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = " "
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = " "
format = 'via [ $symbol ($version) ]($style)'

[python]
symbol = '🐍 '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
